# Generated by Django 5.0.6 on 2026-08-28 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='games', to='catalog.developer')),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='catalog.genre')),
                ('publishers', models.ManyToManyField(blank=True, related_name='games', to='catalog.publisher')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='catalog.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/screenshots/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='catalog.game')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=200)),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='catalog.game')),
            ],
        ),
    ]
