# Generated by Django 5.2.11 on 2026-09-08 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_raw_payload_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('provider_payment_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'created'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('refunded', 'refunded')], default='created', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('review_required', models.BooleanField(default=False)),
                ('review_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
